### ISSUE TITLE
Regular expression conditions sometimes fail to process correctly

### ISSUE THREAD

**Issue by backspace** [travis-ci/travis-conditions#11]
This is also a continuation from #7. If you look at [this build](https://travis-ci.org/backspace/travixperiments-redux/builds/415510827):

![image](https://user-images.githubusercontent.com/43280/44042734-a836f4d0-9ee6-11e8-9f9a-1a93958e8661.png)

which had the [following `.travis.yml`](https://raw.githubusercontent.com/backspace/travixperiments-redux/hello-third/.travis.yml):

```
script: true

stages:
  - name: Jorts
    if: type = cron OR (commit_message =~ /jortleby/) OR (tag IS present AND tag =~ /^hello/)
  - Jants
  - okay

jobs:
  include:
    - stage: Jorts
      script: /bin/true
    - stage: Jants
      script: /bin/true
    - stage: okay
      script: /bin/true
```

and the tag `hello-third`, notice that there is no `Jorts` stage that gets run, despite that `tag IS present AND tag =~ /^hello/)`.

But I’m p confused really so maybe I’m missing something 🙃
