### ISSUE TITLE
commit_message in PR builds doesn't get tip-of-branch but meaningless merge commit message

### ISSUE THREAD

**Issue by andrevmatos** [travis-ci/travis-conditions#7]
It worked until recently, then something changed in the last ~7 days which made the `commit_message` maybe get the `Merge <pr_commit> into <base_commit>` message instead of the message in PR's HEAD, and any condition which depends on a regex on commit_message stopped working.

**Comment by andrevmatos** [comment]
Further investigation have shown this isn't the actual issue, but istead `... OR... (... AND ...)` mix of OR and AND conditions, wrong parsing of the parenthesis expression, or our `tag` regex here:
```
stages:
  ...
  - name: integration
    if: type = cron OR commit_message =~ /\[ci integration\]/ OR (tag IS present AND tag =~ /^v[\d]+\.[\d]+\.[\d]+/)
```
It made the whole condition fails always. Anyway, changing it to a simpler condition in https://github.com/raiden-network/raiden/pull/2002 brought back the `commit_message`, and it even works on top of the merge-commit (meaning the actual, `--no-merges` commit is assigned to `commit_message` instead of the merge commit being tested, which is what we expected).
Closing this, then, but I expect the larger conditions, which is in compliance with the documentation, gets fixed altogether.
